<?php
/**
 * @category  Collab
 * @package   Collab\GoogleOneTap
 * @author    Marcin Jędrzejewski <m.jedrzejewski@collab.pl>
 * @copyright 2024 Collab
 * @license   MIT
 */

/** @var Template $block */
/** @var SecureHtmlRenderer $secureRenderer */

use Collab\GoogleOneTap\ViewModel\GoogleOneTapConfig;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var GoogleOneTapConfig $viewModel */
$viewModel = $block->getViewModel();
$formKey = $viewModel->getFormKey();
$postAuthUrl = $viewModel->getCallbackUrl();
$clientId = $viewModel->getClientId();
?>

<div id="g_id_onload"
     data-client_id="<?= /** @noEscape  */ $clientId ?>"
     data-login_uri="<?= /** @noEscape  */ $postAuthUrl ?>"
     data-form_key="<?= /** @noEscape  */ $formKey ?>"
     data-use_fedcm_for_prompt="true"
     data-auto_prompt="false"
     data-ux_mode="popup"
     data-context="use">
</div>

<?php
$scriptString = <<<SCRIPT
(events => {
    const loadOneTapJs = () => {
        events.forEach(type => window.removeEventListener(type, loadOneTapJs))
        element = document.createElement('script');
        scriptTag = document.getElementsByTagName('script')[0];

        element.async = true;
        element.src = 'https://accounts.google.com/gsi/client';

        scriptTag.parentNode.insertBefore(element, scriptTag);
    };
    events.forEach(type => window.addEventListener(type, loadOneTapJs, {once: true, passive: true}))
})(['touchstart', 'mouseover', 'wheel', 'scroll', 'keydown'])
SCRIPT;
?>

<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
