<?php
/**
 * @category  Collab
 * @package   Collab\GoogleOneTap
 * @author    Marcin Jędrzejewski <m.jedrzejewski@collab.pl>
 * @copyright 2024 Collab
 * @license   MIT
 */

/** @var Template $block */

use Magento\Framework\View\Element\Template;
?>

<div class="g_id_signin"
     data-type="icon"
     data-shape="circle"
     data-theme="outline"
     data-text="continue_with"
     data-size="large">
</div>
